[package]
name = "krugerreto"
version = "0.1.0"
authors = ["Jair <jair.quinonez@epn.edu.ec>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
